"""
Django settings for travixpay project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wk5z+=kc#j@vfp8ge!(n_c+65q*2ctv4n^ruhf09yb%bucb^9('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # TravixPay Apps
    'accounts',
    'wallets',
    'payments',
    'cards',
    'terminals',
    'events',
    'audit',
    'admin_panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travixpay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travixpay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom Authentication User Model
AUTH_USER_MODEL = 'accounts.User'

# Cache: LocMemCache for hackathon (no Redis required)
# For production, switch to Redis cache backend
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Payment Confirmation Mode
# VERIFY_ONLY: Callback verifies payment via Nomba API, credits wallet immediately
# WEBHOOK_REQUIRED: Webhook is source of truth, callback only shows status
PAYMENT_CONFIRMATION_MODE = os.environ.get('PAYMENT_CONFIRMATION_MODE', 'VERIFY_ONLY')

# Site URL for absolute URLs (callbackUrl, etc.)
# In production, set to your domain: https://yourdomain.com
# In sandbox/dev, defaults to http://127.0.0.1:8000
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# Nomba Integration Configuration
NOMBA_ENV = os.environ.get('NOMBA_ENV', 'sandbox')
NOMBA_CLIENT_ID = os.environ.get('NOMBA_CLIENT_ID', 'test-client-id')
NOMBA_CLIENT_SECRET = os.environ.get('NOMBA_CLIENT_SECRET', 'test-client-secret')
NOMBA_PARENT_ACCOUNT_ID = os.environ.get('NOMBA_PARENT_ACCOUNT_ID', 'test-parent-account-id')
NOMBA_WEBHOOK_SECRET = os.environ.get('NOMBA_WEBHOOK_SECRET', 'test-webhook-secret')

# TravixPay Platform Status
SYSTEM_STATUS = 'HEALTHY'  # Can be DEGRADED on startup check failures

# Configurable offline tap rules
OFFLINE_TAP_MAX_RIDES = 2
OFFLINE_TAP_MAX_DEBT = Decimal('1000.00')

# Logging configurations
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'payment_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'payment.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'payments': {
            'handlers': ['console', 'payment_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'terminals': {
            'handlers': ['console', 'payment_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


