# Generated by Django 6.0.6 on 2026-06-24 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('terminals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtaplog',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tap_logs', to='terminals.terminal'),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardtaplog',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='cards.rfidcard'),
        ),
    ]
